### ISSUE TITLE
Need to use GET method as URI params 

### ISSUE THREAD

**Issue by suruchi10** [restDSL/rest_dsl_gem#2]
I am facing trouble in automating one of the scenario where API is GET and using URI params .
like :- https://something.com/policysearch/api/policy/23456/dateofloss/08092019

I just want to confirm can we handle this using current rest dsl implementation or it needs to be modify . 
If yes could you please send me a snippet of example code which can handle this situation.

**Comment by Castone22** [comment]
Testing some stuff around this atm because i believe it's bugged...

Spec is supposed to look like
```ruby
class MyRestService < Service::Base
  rest_call(:get, :path_params, 'get/:person/:id')
end

MyRestService.get_param_paths(url_args: {person: 'foo', id: 1})
```

But when we run that apparently there's a malformed url getting created.  I'm delving into why that happens.

**Comment by Castone22** [comment]
Didn't mean to close this
