### ISSUE TITLE
Putting Environment File Name in a Project Config File

### ISSUE THREAD

**Issue by rmankkar** [restDSL/rest_dsl_gem#5]
Hi Luke,

Can we modify this Gem so that "config/rest_dsl.yml" files' name '**rest_dsl**' is configurable in Project which is using this Gem? We want to test all existing SPEC Files but with a different set of Environments and I want to point the SPEC Files to read from a different environment file as needed.

Let me know if it is feasible without breaking the essence of this gem.

Regards,
Rishi Mankkar

**Comment by Castone22** [comment]
So essentially you want something like 'config/rest_dsl.test.yaml', 'config/rest_dsl.dev.yaml'
It's actually technically possible to accomplish this with the current design of the gem.  If you did something like
```ruby
environment = ENV['TEST_ENV'].downcase
RestDSL.config_file_location = "./config/#{environment}"
```
```
|\config
| |\ dev
| | | rest_dsl.yaml
| |\ test
| | | rest_dsl.yaml
```
If this isn't adequate for your needs we could look into another solution though.

**Comment by rmankkar** [comment]
Thanks Luke for the reply. I will try to complete my goal using the code suggestion given by you.

**Comment by Castone22** [comment]
For now since this has been silent for a little under a year, i'm going to go ahead and close this assuming this was adequate for your case.

I went ahead and added a page about it to the wiki
https://github.com/restDSL/rest_dsl_gem/wiki/Multi-Environment-Configs
