### ISSUE TITLE
Putting payload in delete method in rest-client/lib/resource.rb

### ISSUE THREAD

**Issue by Reetu-Centric** [restDSL/rest_dsl_gem#6]
Hi Luke,

Can we modify delete method  from (\rest-client-2.1.0-x64-mingw32\lib\restclient\resource.rb ) by adding payload ,so that we can pass the payload through the request ? We want to test scenarios where we have payload in delete.

Let me know if it is feasible .

Regards,
Reetu

**Comment by LukeIGS** [comment]
I don't see any reason why not, but i have to dig into ruby rest client to ensure that it actually allows bodies on delete requests in the first place... i'm not entirely sure it does, will get back to you.

**Comment by LukeIGS** [comment]
Oh, that's actually in the lib itself... hmm, we'd have to make a PR to rest-client gem or monkeypatch it on our end.

**Comment by LukeIGS** [comment]
Looking through our code, could you try modifying and removing the delete key from that array
```
https://github.com/restDSL/rest_dsl_gem/blob/master/lib/rest_dsl/client.rb#L20
```
on your local instance and see if that allows you to send a delete request with a payload?  I don't have any rest services on my network that take delete with a body.

**Comment by Reetu-Centric** [comment]
I have tried using the payload after removing the delete key from the array but still its not working.

![image](https://user-images.githubusercontent.com/68987581/118655631-5a0cc400-b807-11eb-891b-8f7b096ab6e1.png)

**Comment by Reetu-Centric** [comment]
as we are not passing payload in delete method at \rest-client-2.1.0-x64-mingw32\lib\restclient\resource.rb and  \rest-client-2.1.0-x64-mingw32\spec\unit\restclient\resource_spec.rb 

Please find the attached screenshot 
![image](https://user-images.githubusercontent.com/68987581/118656041-c4bdff80-b807-11eb-99ef-e05adc760f14.png)

![image](https://user-images.githubusercontent.com/68987581/118656142-dc958380-b807-11eb-90dc-e04a7e122a54.png)

**Comment by Castone22** [comment]
yeah, the code you attached isn't in our lib, it's part of rest-client itself, the underlying library, i'd have to direct you there, however we don't actually *use* resource.rb at all, we use RestClient::Request.new(args).execute.

https://github.com/restDSL/rest_dsl_gem/blob/master/lib/rest_dsl/client.rb#L42

Whether or not restDSL will forward a call to rest client or not is solely driven by the content of the array which is referenced from method_has_payload
https://github.com/restDSL/rest_dsl_gem/blob/master/lib/rest_dsl/client.rb#L37

I don't really like the idea of monkeypatching rest_client in our library to support delete payloads if it doesn't out of box.  We probably need to open an issue with them to add support for doing so.

**Comment by Castone22** [comment]
After some digging this isn't even caused by rest-client gem, looks like the ruby Net::HTTP client itself doesn't allow bodies to be sent in delete requests.
https://github.com/ruby/net-http/blob/master/lib/net/http/requests.rb#L40

Given this is ruby, you may be able to get away with defining a monkeypatch containing
```ruby
Net::HTTP::Delete::REQUEST_HAS_BODY = true
```
somewhere in your code to enable payloads to send in delete requests.  It's definitely going to raise a warning though.

**Comment by Reetu-Centric** [comment]
Thanks luke, for the update will try to use the(Net::HTTP::Delete::REQUEST_HAS_BODY = true) code in our script and will let you know

**Comment by Castone22** [comment]
@Reetu-Centric Any update on this?

**Comment by Reetu-Centric** [comment]
Hey Luke ,
I tried changing the Net::HTTP::Delete::REQUEST_HAS_BODY = true but still getting error as we have to pass payload in Delete method in restclient, I am still checking where all we have to make changes in Delete method so that we can pass payload with delete.
will update soon on same.

**Comment by LukeIGS** [comment]
I'm a little curious what error you're getting, i just executed the following script
```ruby
require 'rest-client'
require 'json'

Net::HTTP::Delete::REQUEST_HAS_BODY = true

res = RestClient::Request.new(method: :delete, url: 'https://postman-echo.com/delete', payload: {"foo": "bar"}.to_json).execute
p JSON.parse(res)
```
And it returned
```json
{"args"=>{}, "data"=>"", "files"=>{}, "form"=>{"{\"foo\":\"bar\"}"=>""}, "headers"=>{"x-forwarded-proto"=>"https", "x-forwarded-port"=>"443", "host"=>"postman-echo.com", "x-amzn-trace-id"=>"Root=1-60a7a1ae-44844cfc4499ae614af1f78b", "content-length"=>"13", "accept"=>"*/*", "user-agent"=>"rest-client/2.1.0 (mingw32 x86_64) ruby/2.7.1p83", "accept-encoding"=>"gzip;q=1.0,deflate;q=0.6,identity;q=0.3", "content-type"=>"application/x-www-form-urlencoded"}, "json"=>{"{\"foo\":\"bar\"}"=>""}, "url"=>"https://postman-echo.com/delete"}
```

This is, under the covers, what RestDSL should pass to RestClient provided the earlier mentioned value in the array of requests that have bodies doesn't include delete.

**Comment by LukeIGS** [comment]
#7 will change RestDSL to query Net::HTTP configs to determine whether or not delete requests are allowed to have bodies instead of just hardcoding it.  That means provided 
```ruby
Net::HTTP::Delete::REQUEST_HAS_BODY = true
```
was called at any point before the request is made, it would allow a payload to be passed, i've added an integration test that shows this at 
https://github.com/restDSL/rest_dsl_gem/blob/a5a59a9e8713fd8c188250fab06e478b4300792d/spec/service_base_spec.rb#L120

Going to cut a new release soon containing this implementation.

**Comment by LukeIGS** [comment]
Release 1.10 is up with this new logic.
